#использование базового образа убунты
FROM ubuntu:22.04

#установка необходимых программ с помощью apt-get
RUN apt-get update && apt-get install -y \
    python3.9=3.9.17~22.04 \
    python3-pip=22.0.2+dfsg-1ubuntu0.4 \
    git=1:2.34.1-1ubuntu1.10

#установка необходимых пакетов и зависимостей
RUN pip install flask==2.3.3 \
    flask_login==0.6.3 \
    lti==0.9.5 \
    celery==5.3.4

#клонирование репозитория из GitHub
RUN git clone https://github.com/moevm/devops-examples.git

#указание рабочей директории
WORKDIR /devops-examples/EXAMPLE_APP

#копирование файлов проекта в текущую директорию
COPY . .

#применение патч-файла
RUN patch main.py patch_file.patch

#команда, которая будет выполнена при запуске контейнера на основе этого образа
CMD ["bash", "-c", "/usr/bin/python3 main.py"]
